package arrayprograms;

public class Trycatchexception {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int b=4;
		int c=0;
		try
		{
			int k=b/c;
			
		}
		catch(ArithmeticException h)
		{
			System.out.println("i am a arthmetic error");
		}
	catch(Exception d)
		{
		System.out.println("i am a catched error");
		}
		
		}
		
	

}
